name: Tweet Wallpaper Daily

on:
  schedule:
    - cron: "30 14,17 * * *"

  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Post to Twitter
        env:
          TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          PICTURE_DB: "2ed8fb2e29c928a3892d77c9a633752c"
          PICTURE_DB_URL: "https://raw.githubusercontent.com/ArunBalajiR/Twitter-Bot/master/photos_unposted.json"
        run: python ./post.py
